FROM openjdk
EXPOSE 8533
VOLUME /tmp
ADD game-record/target/game-record.jar /app.jar
RUN bash -c 'touch /app.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-Duser.timezone=GMT+8","-jar","/app.jar"]
