FROM openjdk
EXPOSE 8544
VOLUME /tmp
ADD lottery-settle/target/settle.jar /app.jar
RUN bash -c 'touch /app.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-Duser.timezone=GMT+8","-jar","/app.jar"]
